# Pre-commit hooks for code quality and architectural rules
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      # Run linter
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      
      # Run formatter
      - id: ruff-format
        types_or: [python, pyi]

  # Import rule checker - Custom architectural validation
  - repo: local
    hooks:
      - id: import-rules
        name: Check import rules (presentation layer)
        entry: python scripts/check_import_rules.py
        language: python
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        verbose: true

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # File checks
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1000]
      
      # Python checks
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
        args: [--pytest-test-first]

  # Type checking with mypy (optional)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.14.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-all]
  #       args: [--ignore-missing-imports, --no-strict-optional]

# Configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [import-rules]  # Skip custom local hooks in CI
  submodules: false
