"""
Status View Styles - Modular organization.

This package contains all styling for the unified status views,
split into logical modules for better maintainability.
"""

from .status_containers import (
    STATUS_VIEW_CONTAINER_STYLE,
)
from .status_cards import (
    CARDS_SECTION_SCROLL_STYLE,
    CARDS_SECTION_TITLE_PASSED_STYLE,
    CARDS_SECTION_TITLE_FAILED_STYLE,
    get_test_card_style,
    TEST_CARD_LABEL_HEADER_STYLE,
    TEST_CARD_LABEL_STATUS_PASSED_STYLE,
    TEST_CARD_LABEL_STATUS_FAILED_STYLE,
    TEST_CARD_LABEL_METRIC_STYLE,
)
from .status_widgets_styles import (
    # Status Header
    STATUS_HEADER_TIME_LABEL_STYLE,
    STATUS_HEADER_ETA_LABEL_STYLE,
    STATUS_HEADER_SPEED_LABEL_STYLE,
    STATUS_HEADER_COMPLETION_LABEL_STYLE,
    STATUS_HEADER_PASSED_LABEL_STYLE,
    STATUS_HEADER_FAILED_LABEL_STYLE,
    STATUS_HEADER_SECTION_STYLE,
    # Performance Panel
    PERFORMANCE_PANEL_SUMMARY_LABEL_STYLE,
    PERFORMANCE_PANEL_TOGGLE_BUTTON_STYLE,
    PERFORMANCE_PANEL_SECTION_STYLE,
    # Worker Progress
    WORKER_LABEL_STYLE,
    WORKER_TEST_LABEL_IDLE_STYLE,
    WORKER_TEST_LABEL_ACTIVE_STYLE,
    WORKER_TIME_LABEL_IDLE_STYLE,
    WORKER_TIME_LABEL_ACTIVE_STYLE,
    get_worker_progress_container_style,
    # Visual Progress Bar
    PROGRESS_BAR_LEGEND_PASSED_STYLE,
    PROGRESS_BAR_LEGEND_FAILED_STYLE,
    VISUAL_PROGRESS_BAR_SECTION_STYLE,
    get_progress_segment_style,
    # Test Results Cards
    CARDS_SECTION_PASSED_TITLE_STYLE,
    CARDS_SECTION_FAILED_TITLE_STYLE,
    CARDS_SECTION_EMPTY_LABEL_STYLE,
    CARDS_SECTION_SCROLLBAR_STYLE,
    TEST_RESULTS_CARDS_SECTION_STYLE,
)

__all__ = [
    # Containers
    "STATUS_VIEW_CONTAINER_STYLE",
    # Cards
    "CARDS_SECTION_SCROLL_STYLE",
    "CARDS_SECTION_TITLE_PASSED_STYLE",
    "CARDS_SECTION_TITLE_FAILED_STYLE",
    "get_test_card_style",
    "TEST_CARD_LABEL_HEADER_STYLE",
    "TEST_CARD_LABEL_STATUS_PASSED_STYLE",
    "TEST_CARD_LABEL_STATUS_FAILED_STYLE",
    "TEST_CARD_LABEL_METRIC_STYLE",
    # Status Header (V2 Widgets)
    "STATUS_HEADER_TIME_LABEL_STYLE",
    "STATUS_HEADER_ETA_LABEL_STYLE",
    "STATUS_HEADER_SPEED_LABEL_STYLE",
    "STATUS_HEADER_COMPLETION_LABEL_STYLE",
    "STATUS_HEADER_PASSED_LABEL_STYLE",
    "STATUS_HEADER_FAILED_LABEL_STYLE",
    "STATUS_HEADER_SECTION_STYLE",
    # Performance Panel (V2 Widgets)
    "PERFORMANCE_PANEL_SUMMARY_LABEL_STYLE",
    "PERFORMANCE_PANEL_TOGGLE_BUTTON_STYLE",
    "PERFORMANCE_PANEL_SECTION_STYLE",
    # Worker Progress (V2 Widgets)
    "WORKER_LABEL_STYLE",
    "WORKER_TEST_LABEL_IDLE_STYLE",
    "WORKER_TEST_LABEL_ACTIVE_STYLE",
    "WORKER_TIME_LABEL_IDLE_STYLE",
    "WORKER_TIME_LABEL_ACTIVE_STYLE",
    "get_worker_progress_container_style",
    # Visual Progress Bar (V2 Widgets)
    "PROGRESS_BAR_LEGEND_PASSED_STYLE",
    "PROGRESS_BAR_LEGEND_FAILED_STYLE",
    "VISUAL_PROGRESS_BAR_SECTION_STYLE",
    "get_progress_segment_style",
    # Test Results Cards (V2 Widgets)
    "CARDS_SECTION_PASSED_TITLE_STYLE",
    "CARDS_SECTION_FAILED_TITLE_STYLE",
    "CARDS_SECTION_EMPTY_LABEL_STYLE",
    "CARDS_SECTION_SCROLLBAR_STYLE",
    "TEST_RESULTS_CARDS_SECTION_STYLE",
]
