"""
Status View Styles - Modular organization.

This package contains all styling for the unified status views,
split into logical modules for better maintainability.
"""

from .status_containers import (
    STATUS_VIEW_CONTAINER_STYLE,
    CONTROLS_PANEL_STYLE,
    FILE_BUTTON_STYLE,
    SECTION_HEADER_STYLE,
)
from .status_progress import (
    PROGRESS_SECTION_CONTAINER_STYLE,
    VISUAL_PROGRESS_BAR_STYLE,
    SEGMENT_DEFAULT_STYLE,
    get_segment_style,
    STATS_PANEL_STYLE,
    STATS_LABEL_PASSED_STYLE,
    STATS_LABEL_FAILED_STYLE,
    STATS_PERCENTAGE_STYLE,
)
from .status_cards import (
    CARDS_SECTION_SCROLL_STYLE,
    CARDS_SECTION_TITLE_PASSED_STYLE,
    CARDS_SECTION_TITLE_FAILED_STYLE,
    get_test_card_style,
    TEST_CARD_LABEL_HEADER_STYLE,
    TEST_CARD_LABEL_STATUS_PASSED_STYLE,
    TEST_CARD_LABEL_STATUS_FAILED_STYLE,
    TEST_CARD_LABEL_METRIC_STYLE,
)

__all__ = [
    # Containers
    "STATUS_VIEW_CONTAINER_STYLE",
    "CONTROLS_PANEL_STYLE",
    "FILE_BUTTON_STYLE",
    "SECTION_HEADER_STYLE",
    # Progress
    "PROGRESS_SECTION_CONTAINER_STYLE",
    "VISUAL_PROGRESS_BAR_STYLE",
    "SEGMENT_DEFAULT_STYLE",
    "get_segment_style",
    "STATS_PANEL_STYLE",
    "STATS_LABEL_PASSED_STYLE",
    "STATS_LABEL_FAILED_STYLE",
    "STATS_PERCENTAGE_STYLE",
    # Cards
    "CARDS_SECTION_SCROLL_STYLE",
    "CARDS_SECTION_TITLE_PASSED_STYLE",
    "CARDS_SECTION_TITLE_FAILED_STYLE",
    "get_test_card_style",
    "TEST_CARD_LABEL_HEADER_STYLE",
    "TEST_CARD_LABEL_STATUS_PASSED_STYLE",
    "TEST_CARD_LABEL_STATUS_FAILED_STYLE",
    "TEST_CARD_LABEL_METRIC_STYLE",
]
